### ISSUE TITLE
denon start errors

### ISSUE THREAD

**Issue by Daniel-Knights** [denosaurs/denon#109]
When running `denon start`, I get these errors:
```bash
[*] [main] v2.4.4
[*] [daem] watching path(s): *.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run app.ts`
Check file:///Users/danknights/Desktop/deno_oak/app.ts
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.53.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.53.0/path/posix.ts:433:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Response,
  ~~~~~~~~
    at https://deno.land/x/oak/deps.ts:9:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Cookies,
  ~~~~~~~
    at https://deno.land/x/oak/deps.ts:20:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Cookie,
  ~~~~~~
    at https://deno.land/x/oak/deps.ts:21:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Key,
  ~~~
    at https://deno.land/x/oak/deps.ts:46:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ParseOptions,
  ~~~~~~~~~~~~
    at https://deno.land/x/oak/deps.ts:48:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  TokensToRegexpOptions,
  ~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/deps.ts:50:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ApplicationOptions,
  ~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:5:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ListenOptions,
  ~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:6:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ListenOptionsBase,
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:7:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ListenOptionsTls,
  ~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:8:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  State,
  ~~~~~
    at https://deno.land/x/oak/mod.ts:9:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Context, ContextSendOptions } from "./context.ts";
                  ~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:11:19

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  CookiesGetOptions,
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:14:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  CookiesSetDeleteOptions,
  ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:15:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { compose as composeMiddleware, Middleware } from "./middleware.ts";
                                       ~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:18:40

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Body,
  ~~~~
    at https://deno.land/x/oak/mod.ts:20:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  BodyOptions,
  ~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:21:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  BodyOptionsAsReader,
  ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:22:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  BodyReader,
  ~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:23:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  BodyType,
  ~~~~~~~~
    at https://deno.land/x/oak/mod.ts:24:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  RouteParams,
  ~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:29:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Route,
  ~~~~~
    at https://deno.land/x/oak/mod.ts:30:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  RouterContext,
  ~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:32:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  RouterMiddleware,
  ~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:33:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ErrorStatus, HTTPMethods, RedirectStatus } from "./types.d.ts";
         ~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:36:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ErrorStatus, HTTPMethods, RedirectStatus } from "./types.d.ts";
                      ~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:36:23

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { ErrorStatus, HTTPMethods, RedirectStatus } from "./types.d.ts";
                                   ~~~~~~~~~~~~~~
    at https://deno.land/x/oak/mod.ts:36:36

Found 31 errors.
[E] [daem] app crashed - waiting for file changes before starting ...
```

I've tried reinstalling/upgrading both deno and denon.

All other commands seem to work fine except this.

---

I'm just using a basic `scripts.json` file:
```json
{
  "$schema": "https://deno.land/x/denon/schema.json",
  "scripts": {
    "start": {
      "cmd": "deno run app.ts",
      "desc": "run my app.ts file"
    }
  }
}
```

And `app.ts`:
```js
import { Application } from 'https://deno.land/x/oak/mod.ts';

const app = new Application();

// Logger
app.use(async (ctx, next) => {
	await next();
	const rt = ctx.response.headers.get('X-Response-Time');
	console.log(`${ctx.request.method} ${ctx.request.url} - ${rt}`);
});

app.use(ctx => {
	console.log(ctx.request);
	ctx.response.body = 'Hello World!';
});

await app.listen({ port: 3000 });
```

**Comment by Daniel-Knights** [comment]
Sorry, this seems to be an issue with deno or oak.

**Comment by boyarzun** [comment]
I was thinking the same thing, it might be a bug, but then I found this link and fixed the problem. I hope I can help.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports
