### ISSUE TITLE
Bad file descriptor (os error 9)

### ISSUE THREAD

**Issue by potatojoayo** [denosaurs/denon#127]
**Bug Description**

Can't run denon for the error. 
I'm currently using docker. The image of deno is **hayd/alpine-deno:1.7.2**
I also tried other images using other os, different deno and denon version also show the error.
Every environment made the same result, bad file descriptor (os error 9)

**To Reproduce** Steps to reproduce the behavior: 
1.  `$ denon` alone works fine.
2. `$ deno run src/main.ts` works fine too.
3. `$ denon deno run src/main.ts` doesn't run and shows the error.

**Expected behavior** 
Running without any error.

**Configuration or Project**

**Screenshots**

api          | [*] [main] v2.4.7
api          | [*] [daem] watching path(s): **/*.*
api          | [*] [daem] watching extensions: ts,tsx,js,jsx,json
api          | [!] [#0] starting `deno run src/main.ts`
api          | error: Uncaught (in promise) Error: Bad file descriptor (os error 9)
api          |     throw new ErrorClass(res.err.message);
api          |           ^
api          |     at processResponse (deno:core/core.js:213:11)
api          |     at Object.jsonOpSync (deno:core/core.js:236:12)
api          |     at new FsWatcher (deno:runtime/js/40_fs_events.js:13:24)
api          |     at Object.watchFs (deno:runtime/js/40_fs_events.js:49:12)
api          |     at run (https://deno.land/x/denon@2.4.7/src/watcher.ts:145:38)
api          |     at Watcher.denoWatch (https://deno.land/x/denon@2.4.7/src/watcher.ts:156:5)
api          |     at Watcher.iterate (https://deno.land/x/denon@2.4.7/src/watcher.ts:122:16)
api          |     at iterate.next (<anonymous>)
api          |     at Daemon.iterate (https://deno.land/x/denon@2.4.7/src/daemon.ts:172:24)
api          |     at async https://deno.land/x/denon@2.4.7/denon.ts:167:20

**Setup**

- OS: alpine linux
- Deno version: 1.7.2
- Denon version: v2.4.7

**Comment by potatojoayo** [comment]
https://github.com/potatojoayo/udemy_deno_docker

Here are my codes trying to run denon via docker
