### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Songkeys** [denosaurs/denon#137]
```
➜ deno --version
deno 1.10.1 (release, x86_64-apple-darwin)
v8 9.1.269.27
typescript 4.2.2
```

```
➜ deno install -qAf --unstable https://deno.land/x/denon/denon.ts
Warning Implicitly using latest version (2.4.8) for https://deno.land/x/denon/denon.ts
error: TS18022 [ERROR]: A method cannot be named with a private identifier.
  #tryGrowByReslice(n: number) {
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.99.0/io/buffer.ts:85:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #reslice(len: number) {
  ~~~~~~~~
    at https://deno.land/std@0.99.0/io/buffer.ts:94:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #grow(n: number) {
  ~~~~~
    at https://deno.land/std@0.99.0/io/buffer.ts:141:3

Found 3 errors.
```

**Comment by crowlKats** [comment]
You are using a fairly outdated version of deno

**Comment by Songkeys** [comment]
Is denon planned to support the latest version of deno? If so, can we change the README claim?

> ⚠️ Make sure you are using deno version ^1.4.0 to install this executable. You can upgrade running deno upgrade.
