### ISSUE TITLE
Failed to install with Deno 1.14.0

### ISSUE THREAD

**Issue by kamekyame** [denosaurs/denon#139]
**Describe the bug** 
Failed to install with Deno 1.14.0

**To Reproduce**
1\. Install or update to deno v1.14.0
2\. `deno install -qAf --unstable https://deno.land/x/denon/denon.ts`
3\. I get the following error
```console
error: TS2345 [ERROR]: Argument of type 'number' is not assignable to parameter of type 'string'.
        p.kill(9);
               ^
    at https://deno.land/x/denon@2.4.8/src/daemon.ts:92:16

TS2345 [ERROR]: Argument of type 'number' is not assignable to parameter of type 'string'.
        p.kill(9);
               ^
    at https://deno.land/x/denon@2.4.8/src/daemon.ts:96:16

TS2551 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'signal'?
        Deno.Signal.SIGHUP,
             ~~~~~~
    at https://deno.land/x/denon@2.4.8/src/daemon.ts:150:14

    'signal' is declared here.
      export function signal(sig: Signal): SignalStream;
                      ~~~~~~
        at asset:///lib.deno.unstable.d.ts:651:19

TS2551 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'signal'?
        Deno.Signal.SIGINT,
             ~~~~~~
    at https://deno.land/x/denon@2.4.8/src/daemon.ts:151:14

    'signal' is declared here.
      export function signal(sig: Signal): SignalStream;
                      ~~~~~~
        at asset:///lib.deno.unstable.d.ts:651:19

TS2551 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'signal'?
        Deno.Signal.SIGTERM,
             ~~~~~~
    at https://deno.land/x/denon@2.4.8/src/daemon.ts:152:14

    'signal' is declared here.
      export function signal(sig: Signal): SignalStream;
                      ~~~~~~
        at asset:///lib.deno.unstable.d.ts:651:19

TS2551 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag, or did you mean 'signal'?
        Deno.Signal.SIGTSTP,
             ~~~~~~
    at https://deno.land/x/denon@2.4.8/src/daemon.ts:153:14

    'signal' is declared here.
      export function signal(sig: Signal): SignalStream;
                      ~~~~~~
        at asset:///lib.deno.unstable.d.ts:651:19

Found 6 errors.
```

**Setup**

- OS: windows
- Deno version: 1.14.0
- Denon version: 2.4.8

**Additional context**
This is probably due to the following pull request modified according to the v1.14.0 release.
https://github.com/denoland/deno/pull/11909

**Comment by yapyeeqiang** [comment]
Facing the same issue

**Comment by jacorall** [comment]
I have the same issue on Ubuntu 20.04 and Deno V1.14.0

**Comment by ksmarty** [comment]
Same issue on MacOS 11.5.2 and Deno 1.14.0

**Comment by luisregardiz** [comment]
Same issue on Windows 10 and Deno v.1.14.0

**Comment by eliassjogreen** [comment]
This should be fixed in the latest release
