### ISSUE TITLE
error: Uncaught (in promise) Error: not implemented p.kill("SIGKILL")

### ISSUE THREAD

**Issue by vsmahesh** [denosaurs/denon#140]
I am getting the following exception in the console

[*] [daem] restarting due to changes...
error: Uncaught (in promise) Error: not implemented
        p.kill("SIGKILL");
          ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at opKill (deno:runtime/js/40_process.js:18:10)
    at Process.kill (deno:runtime/js/40_process.js:92:7)
    at Daemon.killAll (https://deno.land/x/denon@2.4.9/src/daemon.ts:92:11)
    at Daemon.reload (https://deno.land/x/denon@2.4.9/src/daemon.ts:35:10)
    at Daemon.iterate (https://deno.land/x/denon@2.4.9/src/daemon.ts:181:22)
    at iterate.next (<anonymous>)
    at https://deno.land/x/denon@2.4.9/denon.ts:167:20.

- OS: windows 10
- Deno version: deno 1.14.1 (release, x86_64-pc-windows-msvc) v8 9.4.146.15 typescript 4.4.2
- Denon version: v2.4.9

**Comment by nnmrts** [comment]
denon 2.4.9 is incompatible with deno 1.16, this issue can be closed.
