### ISSUE TITLE
Can't install "Denon" Deno "1.17.1"

### ISSUE THREAD

**Issue by Pankaj7288** [denosaurs/denon#156]
### **Can't install "Denon" Deno "1.17.1"**

Issue

![Capture](https://user-images.githubusercontent.com/41538294/147441494-51955073-5d24-4516-85cf-b369bb374031.JPG)

**Comment by UdittLamba** [comment]
same issue with me

**Comment by amm834** [comment]
Same here

**Comment by PixelPage-YT** [comment]
Same

**Comment by e-jigsaw** [comment]
hi, i have same issue.

```
deno install --unstable https://raw.githubusercontent.com/denosaurs/denon/main/denon.ts
```

works for me. maybe deno.land file is old

**Comment by bicarlsen** [comment]
I'm having the same issue. Just wanted to post the error here as text for searchablility.
```bash
error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
  Type '"other"' is not assignable to type 'FileAction'.
            this.#changes[path].push(kind);
                                     ~~~~
    at https://deno.land/x/denon@2.4.10/src/watcher.ts:150:38
```
(The solution from @e-jigsaw worked for me too.)

**Comment by HernanGH** [comment]
Same issue here!

**Comment by nenjotsu** [comment]
Same issue here, can't install

![Screen Shot 2022-01-17 at 8 45 57 PM](https://user-images.githubusercontent.com/26914800/149771841-9643f8e3-237d-4288-8221-7b5edc33fbdb.png)

**Comment by gtrabanco** [comment]
Same on macOS

**Comment by eivindingebrigtsen** [comment]
Same issue with deno v 1.18.0

**Comment by yogesnsamy** [comment]
> `deno install --unstable https://raw.githubusercontent.com/denosaurs/denon/main/denon.ts`

@e-jigsaw I did this and the earlier error is gone, only to be replaced with the following on the IOS. 
Any thoughts on this? Thanks in advance for reading. 

```
denon run --allow-net --allow-env --allow-read --unstable main.ts
⚠️  ️Deno requests read access. Allow? [y/n (y = yes allow, n = no deny)] y
⚠️  ️Deno requests write access. Allow? [y/n (y = yes allow, n = no deny)] y
⚠️  ️Deno requests run access. Allow? [y/n (y = yes allow, n = no deny)] y
[*] [main] v2.4.9
[*] [daem] watching path(s): **/*.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `-f run --allow-net --allow-env --allow-read --unstable main.ts`
error: Uncaught NotFound: No such file or directory (os error 2)
    return Deno.run(options);
                ^
    at Object.opSync (deno:core/01_core.js:149:12)
    at opRun (deno:runtime/js/40_process.js:27:17)
    at Object.run (deno:runtime/js/40_process.js:114:17)
    at Runner.execute (https://raw.githubusercontent.com/denosaurs/denon/main/src/runner.ts:169:17)
    at Object.exe (https://raw.githubusercontent.com/denosaurs/denon/main/src/runner.ts:45:21)
    at Daemon.start (https://raw.githubusercontent.com/denosaurs/denon/main/src/daemon.ts:66:31)
    at Daemon.iterate (https://raw.githubusercontent.com/denosaurs/denon/main/src/daemon.ts:169:32)
    at iterate.next (<anonymous>)
    at https://raw.githubusercontent.com/denosaurs/denon/main/denon.ts:167:20
```

**Comment by e-jigsaw** [comment]
fmm... I can not figure out only error message
