### ISSUE TITLE
Denon install error

### ISSUE THREAD

**Issue by lucasmichot** [denosaurs/denon#161]
**Describe the bug** 

Impossible to install denon

**To Reproduce** 

```sh
deno install -qAf --unstable https://deno.land/x/denon/denon.ts
```

**Logs** 

```SH
> deno install -qAf --unstable https://deno.land/x/denon/denon.ts
error: TS2345 [ERROR]: Argument of type '"any" | "access" | "create" | "modify" | "remove" | "other"' is not assignable to parameter of type 'FileAction'.
  Type '"other"' is not assignable to type 'FileAction'.
            this.#changes[path].push(kind);
                                     ~~~~
    at https://deno.land/x/denon@2.4.7/src/watcher.ts:150:38

TS2345 [ERROR]: Argument of type '9' is not assignable to parameter of type 'Signal'.
        p.kill(9);
               ^
    at https://deno.land/x/denon@2.4.7/src/daemon.ts:92:16

TS2345 [ERROR]: Argument of type '9' is not assignable to parameter of type 'Signal'.
        p.kill(9);
               ^
    at https://deno.land/x/denon@2.4.7/src/daemon.ts:96:16

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
        Deno.Signal.SIGHUP,
             ~~~~~~
    at https://deno.land/x/denon@2.4.7/src/daemon.ts:150:14

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
        Deno.Signal.SIGINT,
             ~~~~~~
    at https://deno.land/x/denon@2.4.7/src/daemon.ts:151:14

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
        Deno.Signal.SIGTERM,
             ~~~~~~
    at https://deno.land/x/denon@2.4.7/src/daemon.ts:152:14

TS2339 [ERROR]: Property 'Signal' does not exist on type 'typeof Deno'. 'Deno.Signal' is an unstable API. Did you forget to run with the '--unstable' flag?
        Deno.Signal.SIGTSTP,
             ~~~~~~
    at https://deno.land/x/denon@2.4.7/src/daemon.ts:153:14

TS2339 [ERROR]: Property 'signal' does not exist on type 'typeof Deno'.
          await Deno.signal(s);
                     ~~~~~~
    at https://deno.land/x/denon@2.4.7/src/daemon.ts:157:22

Found 8 errors.
```

**Setup**

OS: MacOS Monterey 12.3.1
deno 1.20.6 (release, aarch64-apple-darwin)
v8 10.0.139.6
typescript 4.6.2

**Comment by kamekyame** [comment]
@lucasmichot 
This error is from denon@2.4.7. The latest version is 2.5.0. Probably, there is still a previous cache.
You may try reloading the cache with the `-r` option when installing as below.

```
deno install -qAfr --unstable https://deno.land/x/denon/denon.ts
```
or
```
deno install -qAf --unstable https://deno.land/x/denon@2.5.0/denon.ts
```

**Comment by lucasmichot** [comment]
Thanks a lot @kamekyame , I was unaware of this `-r` flag
It might be worth to update the installation instructions and include it ?

**Comment by kamekyame** [comment]
I think be worth it.
Ideally, I would prefer a version-specific installation. 
However, it would be diffecult to maintein the documentation. (Unless there is a good gh actions of release.)
