### ISSUE TITLE
Uncaught NotFound: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Daniel-Knights** [denosaurs/denon#58]
Tried to install as per the docs, didn't work, said:

`Add /Users/danknights/.deno/bin to PATH
    export PATH="/Users/danknights/.deno/bin:$PATH"`

Added the path and tried again, the above message went away, tried `denon init` and got this:
```
[denon] v2.0.2
[denon] watching path(s): *.*
[denon] watching extensions: ts,js,json
[denon] starting `init`
error: Uncaught NotFound: No such file or directory (os error 2)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendSync ($deno$/ops/dispatch_json.ts:72:10)
    at Object.run ($deno$/ops/process.ts:41:10)
    at Object.run ($deno$/process.ts:118:15)
    at Runner.execute (https://deno.land/x/denon/src/runner.ts:117:17)
    at Daemon.start (https://deno.land/x/denon/src/daemon.ts:45:40)
    at Daemon.iterate (https://deno.land/x/denon/src/daemon.ts:122:10)
    at iterate.next (<anonymous>)
    at https://deno.land/x/denon/denon.ts:144:18
```

Is this a bug or am I missing something?

**Comment by Daniel-Knights** [comment]
I was missing something, missed the dashes at the start: `denon --init`.
